name: 'Getting WA-RP+ T'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '52 0/5 * * *'

jobs:
  auto_getting_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking'
        uses: actions/checkout@v2

      - name: 'Setting Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Getting WA-RP+ Traffic'
        env:
          DEVICEID: ${{ secrets.DEVICEID }}      
        run: python warp.py
